name: davlat
description: "App"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  sqlite3: ^2.5.0
  go_router: ^14.6.2
  sqflite: ^2.4.1
  path: ^1.9.0
  # sqflite_common_ffi: ^2.3.4+4
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  in_app_purchase: ^3.2.1
  # yookassa_payments_flutter: ^1.7.1
  firebase_core: ^3.10.1
  uuid: ^4.5.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  flutter_bloc: ^9.0.0
  fluttertoast: ^8.2.10
  intl_phone_field: ^3.2.0
  cloud_firestore: ^5.6.3
  http: ^1.3.0
  url_launcher: ^6.3.1
  # yookassa_payments_flutter: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^2.0.1

icons_launcher:
  image_path: "assets/icons/icon.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/scroll/
    - assets/data/scroll_data.json
    - assets/data/products.json

  # An image asset can refer to one or more resolution-specific "variants", see

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700