// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPzG0zKZero7yFkzBgQZO4XXjJEfFgQjs',
    appId: '1:910508799648:web:7980573eb043e2f4b7fbc5',
    messagingSenderId: '910508799648',
    projectId: 'nike-f75c8',
    authDomain: 'nike-f75c8.firebaseapp.com',
    storageBucket: 'nike-f75c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXAHxWDfYLwF6kRvKB6iVeYxS1jTy-AvA',
    appId: '1:910508799648:android:c6a8e4f5373a835ab7fbc5',
    messagingSenderId: '910508799648',
    projectId: 'nike-f75c8',
    storageBucket: 'nike-f75c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKSCnYJeN5uvYz6Njifn9TwF78d_fOpE',
    appId: '1:910508799648:ios:5ea24acdd8d217bfb7fbc5',
    messagingSenderId: '910508799648',
    projectId: 'nike-f75c8',
    storageBucket: 'nike-f75c8.firebasestorage.app',
    iosBundleId: 'com.example.davlat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKSCnYJeN5uvYz6Njifn9TwF78d_fOpE',
    appId: '1:910508799648:ios:5ea24acdd8d217bfb7fbc5',
    messagingSenderId: '910508799648',
    projectId: 'nike-f75c8',
    storageBucket: 'nike-f75c8.firebasestorage.app',
    iosBundleId: 'com.example.davlat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPzG0zKZero7yFkzBgQZO4XXjJEfFgQjs',
    appId: '1:910508799648:web:22357ef4d14be4ebb7fbc5',
    messagingSenderId: '910508799648',
    projectId: 'nike-f75c8',
    authDomain: 'nike-f75c8.firebaseapp.com',
    storageBucket: 'nike-f75c8.firebasestorage.app',
  );
}
